/// <reference types="tako.sh" />
/**
 * AUTO-GENERATED BY TAKO — DO NOT EDIT
 *
 * Regenerated by the Tako CLI on init, dev, deploy, and `tako typegen`.
 * Manual edits will be overwritten on the next run.
 *
 * TypeScript picks these ambient types up only when your project has a
 * `tsconfig.json`. If you don't have one, run `tsc --init` (or
 * `bunx --bun tsc --init`) at the project root — the default `include`
 * glob covers this file.
 */

type RuntimeMode = "development" | "production";

interface TakoBaseEnv {
  /** Current environment. */
  readonly ENV?: string;
  /** Port the app should listen on — assigned by the Tako runtime. */
  readonly PORT?: string;
  /** Host/address the app should bind to — assigned by the Tako runtime. */
  readonly HOST?: string;
  /** Build identifier injected by Tako at deploy time. Handy for cache busting and error reporting. */
  readonly TAKO_BUILD?: string;
  /** Per-app persistent data directory provided by Tako. Writes survive restarts. */
  readonly TAKO_DATA_DIR?: string;
  /** Resolved log verbosity for this environment, as configured in `tako.toml`. */
  readonly LOG_LEVEL?: "debug" | "info" | "warn" | "error";
}

declare namespace NodeJS {
  interface ProcessEnv extends TakoBaseEnv {
    /** Node runtime alias of ENV. */
    readonly NODE_ENV?: RuntimeMode;
  }
}

interface ImportMetaEnv extends TakoBaseEnv {}

interface ImportMeta {
  /** Tako's env surface exposed via `import.meta.env`. */
  readonly env: ImportMetaEnv;
}
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface TakoSecrets {}
