name = "go-gin-example"
runtime = "go"
main = "app"

[build]
run = "CGO_ENABLED=0 go build -o app ."

[envs.development]
route = "go-gin.test"

[envs.production]
route = "go-gin.tako.sh"
servers = ["tako-demo"]
