/**
 * Tako global API — injected at runtime by the Tako entrypoint.
 *
 * Generated by Tako CLI. Do not edit manually.
 * To update, run `tako init` again or upgrade your Tako CLI.
 */

interface TakoStandardEnv {
  readonly ENV?: string;
  readonly PORT?: string;
  readonly HOST?: string;
  readonly TAKO_ENV?: string;
  readonly TAKO_BUILD?: string;
  readonly TAKO_DATA_DIR?: string;
  readonly NODE_ENV?: "development" | "production";
  readonly TAKO_APP_LOG_LEVEL?: "debug" | "info" | "warn" | "error";
}

declare namespace NodeJS {
  interface ProcessEnv extends TakoStandardEnv {}
}

interface ImportMetaEnv extends TakoStandardEnv {}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface TakoSecrets {}

declare const Tako: {
  secrets: TakoSecrets;
};
