name = "demo"
runtime = "bun"

[[build_stages]]
name = "sdk"
run = "bun run build"
cwd = "../../../sdk/javascript"

[vars.development]
WIDLCARD_SUFFIX = ".tako-demo.tako.test"

[vars.production]
WIDLCARD_SUFFIX = ".demo.tako.sh"

[envs.development]
routes = ["tako-demo.test/foobar", "*.tako-demo.tako.test"]

[envs.production]
routes = ["demo.tako.sh/foobar", "*.demo.tako.sh"]
servers = ["tako-demo"]
