/**
 * Tako global API — injected at runtime by the Tako entrypoint.
 *
 * Generated by Tako CLI. Do not edit manually.
 * To update, run `tako init` again or upgrade your Tako CLI.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface TakoSecrets {}

declare const Tako: {
  secrets: TakoSecrets;
};
