runtime = "bun"

[vars.development]
WIDLCARD_SUFFIX = ".bun-example.tako"

[vars.production]
WIDLCARD_SUFFIX = ".bun.tako.sh"

[vars.staging]
WIDLCARD_SUFFIX = ".bun.tako-testbed.orb.local"

[envs.development]
routes = ["some-app.tako/bun", "*.bun-example.tako"]

[envs.production]
routes = ["demo.tako.sh/bun", "*.bun.tako.sh"]

[envs.staging]
routes = ["tako-testbed.orb.local/bun", "*.bun.tako-testbed.orb.local"]

[servers.tako-demo]
env = "production"

[servers.testbed]
env = "staging"
instances = 2
