name: Release tako-server

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions: {}

jobs:
  release:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/release-cargo.yml
    with:
      crate: tako-server
      directory: tako-server
      bump: ${{ inputs.bump }}
      title: Tako Server
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
